// Centralized image mapping. This file is intended to be generated by the
// image download/optimize script. For now it will attempt to load
// lib/images-generated.json (created by scripts) and export a mapping.
import generated from './images-generated.json';

export type ImageEntry = {
  localJpg?: string;
  variants?: { [width: number]: string };
  blurDataURL?: string;
};

export const IMAGE_MAP: Record<string, ImageEntry> = (generated as Record<string, any>) || {};

export default IMAGE_MAP;
